#!/usr/bin/env bash

mkdir -p /usr/local/lib/nodejs

tar -C /usr/local/lib/nodejs -xvf node.tar.gz

ln -s /usr/local/lib/nodejs/bin/node /usr/bin/node
ln -s /usr/local/lib/nodejs/bin/npm /usr/bin/npm
ln -s /usr/local/lib/nodejs/bin/npx /usr/bin/npx

node -v
npm version
npx -v
